# Generated by Django 3.0.5 on 2020-04-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200412_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Brand', max_length=100),
            preserve_default=False,
        ),
    ]
